language: csharp
sudo: required
dist: trusty
mono: none
dotnet: 1.0.1
services:
  - docker
install:
  - dotnet restore
script:
  - dotnet build
after_success:
  - dotnet publish -o published
  - docker build -t rushi216/aspnetcore-docker .
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push rushi216/aspnetcore-docker
